import React, { useState, useEffect } from 'react';
import {
  FileText,
  Download,
  Calendar,
  Sparkles,
  RefreshCw,
  ExternalLink
} from 'lucide-react';
import { api } from '../services/api';
import { ReportItem } from '../types';

export const Reports: React.FC = () => {
  const [reports, setReports] = useState<ReportItem[]>([]);
  const [selectedReport, setSelectedReport] = useState<ReportItem | null>(null);
  const [loading, setLoading] = useState(true);

  const fetchReports = async () => {
    try {
      setLoading(true);
      const data = await api.reports.list();
      setReports(data);
      if (data.length > 0 && !selectedReport) {
        setSelectedReport(data[0]);
      }
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchReports();
  }, []);

  return (
    <div className="space-y-6 animate-fadeIn max-w-7xl mx-auto">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-slate-200 dark:border-slate-800">
        <div>
          <h1 className="text-2xl font-extrabold text-slate-900 dark:text-white tracking-tight">
            Executive Operations Reports
          </h1>
          <p className="text-xs text-slate-500 dark:text-slate-400 mt-1">
            Publication-ready management summaries synthesized across Finance, Support, and Operations agents.
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Reports List */}
        <div className="bg-white dark:bg-navy-900 rounded-2xl border border-slate-200 dark:border-slate-800 shadow-sm p-4 space-y-3">
          <div className="flex items-center justify-between pb-2 border-b border-slate-100 dark:border-slate-800">
            <h2 className="text-xs font-bold text-slate-900 dark:text-white">Generated Reports</h2>
            <span className="text-[11px] text-slate-400 font-mono">{reports.length} available</span>
          </div>

          {loading && reports.length === 0 ? (
            <div className="p-8 text-center text-xs text-slate-400">Loading reports...</div>
          ) : reports.length === 0 ? (
            <div className="p-8 text-center text-xs text-slate-400">No reports generated yet.</div>
          ) : (
            <div className="space-y-2 overflow-y-auto max-h-[70vh]">
              {reports.map((rep) => {
                const isSelected = selectedReport?.id === rep.id;
                return (
                  <div
                    key={rep.id}
                    onClick={() => setSelectedReport(rep)}
                    className={`p-3.5 rounded-xl border cursor-pointer transition text-xs ${
                      isSelected
                        ? 'border-brand-500 bg-brand-50/40 dark:bg-brand-950/40 shadow-sm'
                        : 'border-slate-200 dark:border-slate-800 hover:bg-slate-50 dark:hover:bg-slate-800/40'
                    }`}
                  >
                    <span className="text-[10px] font-bold uppercase text-brand-600 dark:text-brand-400 block mb-1">
                      {rep.report_type.replace('_', ' ')}
                    </span>
                    <h3 className="font-bold text-slate-900 dark:text-white line-clamp-1">{rep.title}</h3>
                    <p className="text-[11px] text-slate-500 dark:text-slate-400 line-clamp-2 mt-1">
                      {rep.summary}
                    </p>
                    <span className="text-[10px] text-slate-400 mt-2 block font-mono">
                      {new Date(rep.created_at).toLocaleDateString()}
                    </span>
                  </div>
                );
              })}
            </div>
          )}
        </div>

        {/* Report Preview Panel */}
        <div className="lg:col-span-2 bg-white dark:bg-navy-900 rounded-2xl border border-slate-200 dark:border-slate-800 shadow-sm p-6 flex flex-col justify-between">
          {selectedReport ? (
            <div className="space-y-6">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-slate-200 dark:border-slate-800">
                <div>
                  <span className="text-[10px] uppercase font-bold text-brand-600 dark:text-brand-400 tracking-wider">
                    Official Executive Synthesis
                  </span>
                  <h2 className="text-xl font-bold text-slate-900 dark:text-white mt-0.5">
                    {selectedReport.title}
                  </h2>
                  <p className="text-xs text-slate-400 mt-1">
                    Generated by {selectedReport.generated_by_agent} agent on {new Date(selectedReport.created_at).toLocaleString()}
                  </p>
                </div>

                {/* Download Actions */}
                <div className="flex items-center gap-2">
                  <a
                    href={api.reports.getDownloadUrl(selectedReport.id, 'markdown')}
                    target="_blank"
                    rel="noreferrer"
                    className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-slate-200 dark:border-slate-700 hover:bg-slate-100 dark:hover:bg-slate-800 text-xs font-semibold text-slate-700 dark:text-slate-300 transition"
                  >
                    <Download className="w-3.5 h-3.5" />
                    <span>Markdown</span>
                  </a>
                  <a
                    href={api.reports.getDownloadUrl(selectedReport.id, 'html')}
                    target="_blank"
                    rel="noreferrer"
                    className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-brand-600 hover:bg-brand-700 text-white text-xs font-semibold shadow transition"
                  >
                    <Download className="w-3.5 h-3.5" />
                    <span>HTML File</span>
                  </a>
                </div>
              </div>

              {/* Report Markdown Content Preview */}
              <div className="p-6 rounded-xl bg-slate-50 dark:bg-navy-950 border border-slate-200/60 dark:border-slate-800 overflow-y-auto max-h-[60vh] text-xs leading-relaxed space-y-4 whitespace-pre-line text-slate-800 dark:text-slate-200">
                {selectedReport.content}
              </div>
            </div>
          ) : (
            <div className="p-16 text-center text-xs text-slate-400">
              Select a report from the left panel to inspect and download.
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
