from typing import List, Optional
from fastapi import APIRouter, Depends, HTTPException, status, Response, Query
from sqlalchemy.orm import Session

from app.core.database import get_db
from app.core.dependencies import get_current_user
from app.core.security import decode_access_token
from app.models.user import User
from app.models.business import Report
from app.schemas.report import ReportResponse

router = APIRouter(prefix="/reports", tags=["Reports"])


@router.get("", response_model=List[ReportResponse])
def list_reports(
    report_type: Optional[str] = None,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """List generated management and operations reports."""
    query = db.query(Report)
    if report_type:
        query = query.filter(Report.report_type == report_type)
    return query.order_by(Report.created_at.desc()).all()


@router.get("/{report_id}", response_model=ReportResponse)
def get_report(
    report_id: str,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Retrieve full content and metrics of a generated report."""
    rep = db.query(Report).filter(Report.id == report_id).first()
    if not rep:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Report not found")
    return rep


@router.get("/{report_id}/download")
def download_report(
    report_id: str,
    format_type: str = "markdown",
    token: Optional[str] = Query(None),
    db: Session = Depends(get_db),
):
    """Download report file formatted as Markdown or HTML."""
    # Authenticate via query param token or default
    if token:
        payload = decode_access_token(token)
        if not payload or not payload.get("sub"):
            raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid download token")
    rep = db.query(Report).filter(Report.id == report_id).first()
    if not rep:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Report not found")

    safe_title = "".join([c if c.isalnum() else "_" for c in rep.title])

    if format_type.lower() == "html":
        html_content = f"""<!DOCTYPE html>
<html>
<head>
<title>{rep.title}</title>
<style>
body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; line-height: 1.6; color: #1e293b; }}
h1, h2, h3 {{ color: #0f172a; }}
table {{ border-collapse: collapse; width: 100%; margin: 20px 0; }}
th, td {{ border: 1px solid #cbd5e1; padding: 10px; text-align: left; }}
th {{ background-color: #f1f5f9; }}
</style>
</head>
<body>
<h1>{rep.title}</h1>
<p><em>Generated by {rep.generated_by_agent} Agent on {rep.created_at.strftime('%Y-%m-%d %H:%M:%S UTC')}</em></p>
<hr/>
<pre style="white-space: pre-wrap; font-family: inherit;">{rep.content}</pre>
</body>
</html>"""
        return Response(
            content=html_content,
            media_type="text/html",
            headers={"Content-Disposition": f"attachment; filename={safe_title}.html"}
        )

    return Response(
        content=rep.content,
        media_type="text/markdown",
        headers={"Content-Disposition": f"attachment; filename={safe_title}.md"}
    )
